name: semantic-pull-request
author: Jan Amann <jan@amann.me>
description: Ensure your PR title matches the Conventional Commits spec (https://www.conventionalcommits.org/).
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'shield'
  color: 'green'
inputs:
  config:
    description: 'File path for custom config (optional)'
    required: false
