name: 'Publish major version'

on:
  release:
    types: [published, edited]

permissions:
  deployments: write

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@v2
